name: Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: "5 4 * * 1"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: write

    env:
      USER: ${{ github.repository_owner }}
      REPO_NAME: ${{ secrets.REPO }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          pip install -r requirements.txt

      - name: Run scripts
        run: python src/sync.py

      - name: Generate tag
        run: |
          VERSION=$(jq -r '.zhwiki.version'  version.json)
          YEAR=${VERSION:0:4}
          MONTH=${VERSION:4:2}
          DAY=${VERSION:6:2}
          TAG_NAME="v${YEAR}.${MONTH}.${DAY}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "Generated tag: $TAG_NAME"

      - name: Git auto commit
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_message: Automated update
          # commit_options: '--no-verify --signoff'
          # push_options: "--force"
          # file_pattern: "*.json *.docx *.doc"
          tagging_message: ${{ env.TAG_NAME }}
